# Generated by Django 3.0.6 on 2020-06-09 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today)),
                ('edad', models.IntegerField(default=0)),
                ('sexo', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ocupacion', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('calle', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('colonia', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('cp', models.CharField(blank=True, default='', max_length=8, null=True)),
                ('celular', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, default='', null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_proxima_cita', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(default='A', max_length=2)),
            ],
        ),
    ]
