# Generated by Django 3.0.6 on 2020-09-28 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100)),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today)),
                ('edad', models.IntegerField(default=0)),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No definido', 'No definido')], default='No definido', max_length=12, null=True, verbose_name='sexo')),
                ('ocupacion', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('calle', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('colonia', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('cp', models.CharField(blank=True, default='', max_length=8, null=True)),
                ('celular', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('celular2', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('estado', models.CharField(default='Jalisco', max_length=30, null=True)),
                ('pais', models.CharField(default='México', max_length=30, null=True)),
                ('observaciones', models.TextField(blank=True, default='', null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_proxima_cita', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('originario', models.CharField(blank=True, default='', max_length=50)),
                ('medico_particular', models.CharField(blank=True, default='', max_length=50)),
                ('telefono_medico', models.CharField(blank=True, default='', max_length=20)),
                ('motivo_cita', models.CharField(blank=True, default='', max_length=128)),
                ('enfermedad_ultimo_anos', models.CharField(blank=True, default='No', max_length=100)),
                ('enfermedad_grave', models.CharField(blank=True, default='No', max_length=100)),
                ('cirugias', models.CharField(blank=True, default='No', max_length=100)),
                ('traumatismos_secuelas', models.CharField(blank=True, default='No', max_length=100)),
                ('transfusiones', models.CharField(blank=True, default='No', max_length=100)),
                ('hemorragias', models.CharField(blank=True, default='No', max_length=100)),
                ('donador_sangre', models.CharField(blank=True, default='No', max_length=100)),
                ('accidentes_tratamientos', models.CharField(blank=True, default='No', max_length=100)),
                ('tratamiento_medico_padecimientos', models.CharField(blank=True, default='No', max_length=100)),
                ('toma_medicamento', models.CharField(blank=True, default='No', max_length=200)),
                ('enfermedades', models.CharField(blank=True, default='No', max_length=200)),
                ('familiar_enfermedad', models.CharField(blank=True, default='No', max_length=100)),
                ('actualmente_algun_familiar_enfermo', models.CharField(blank=True, default='No', max_length=100)),
                ('actualmente_estaenfermo', models.CharField(blank=True, default='No', max_length=100)),
                ('embarazada', models.CharField(blank=True, default='No', max_length=100)),
                ('higiene', models.CharField(choices=[('Buena', 'Buena'), ('Supervisar', 'Supervisar'), ('Regular', 'Regular'), ('Pendiente', 'Pendiente')], default='Buena', max_length=10)),
                ('numero_cepillados', models.IntegerField(blank=True, default=0)),
                ('alimentacion', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala'), ('Regular', 'Regular'), ('Pendiente', 'Pendiente')], default='Buena', max_length=10)),
                ('integrantes_casa', models.IntegerField(blank=True, default=0)),
                ('practica_deportes', models.CharField(blank=True, default='No', max_length=20)),
                ('habito_adiccion', models.CharField(blank=True, default='No', max_length=100)),
                ('temperatura', models.IntegerField(blank=True, default=0)),
                ('presion', models.IntegerField(blank=True, default=0)),
                ('pulso', models.IntegerField(blank=True, default=0)),
                ('tratamientos_odontologicos', models.CharField(blank=True, default='No', max_length=100)),
                ('alergico_anestesia', models.CharField(blank=True, default='No', max_length=100)),
                ('experiencia_tratamientos', models.CharField(blank=True, default='No', max_length=100)),
                ('articulacion_temporo', models.CharField(blank=True, default='No', max_length=100)),
                ('dolor_articulacion', models.BooleanField(default=False, null=True)),
                ('chasquidos', models.BooleanField(default=False, null=True)),
                ('limitacion_apertura', models.BooleanField(default=False, null=True)),
                ('limitacion_movimientos', models.BooleanField(default=False, null=True)),
                ('bruxismo', models.BooleanField(default=False, null=True)),
                ('obervaciones', models.TextField(blank=True, default='')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(default='A', max_length=2)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', djrichtextfield.models.RichTextField(blank=True)),
                ('obervaciones', models.TextField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(default='A', max_length=2)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente')),
            ],
        ),
    ]
