# Generated by Django 3.1.2 on 2021-01-06 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupaciente',
            name='vence',
            field=models.DateField(default=datetime.datetime(2021, 2, 5, 3, 36, 47, 100777)),
        ),
    ]
