# Generated by Django 3.0.6 on 2020-06-20 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('originario', models.CharField(blank=True, max_length=50, null=True)),
                ('medico_particular', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_medico', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo_cita', models.CharField(blank=True, max_length=128, null=True)),
                ('enfermedad_ultimo_anos', models.CharField(blank=True, max_length=100, null=True)),
                ('enfermedad_grave', models.CharField(blank=True, max_length=100, null=True)),
                ('cirugias', models.CharField(blank=True, max_length=100, null=True)),
                ('traumatismos_secuelas', models.CharField(blank=True, max_length=100, null=True)),
                ('transfusiones', models.CharField(blank=True, max_length=100, null=True)),
                ('hemorragias', models.CharField(blank=True, max_length=100, null=True)),
                ('donador_sangre', models.CharField(blank=True, max_length=100, null=True)),
                ('accidentes_tratamientos', models.CharField(blank=True, max_length=100, null=True)),
                ('tratamiento_medico_padecimientos', models.CharField(blank=True, max_length=100, null=True)),
                ('toma_medicamento', models.CharField(blank=True, max_length=200, null=True)),
                ('enfermedades', models.CharField(blank=True, max_length=200, null=True)),
                ('familiar_enfermedad', models.CharField(blank=True, max_length=100, null=True)),
                ('actualmente_algun_familiar_enfermo', models.CharField(blank=True, max_length=100, null=True)),
                ('actualmente_estaenfermo', models.CharField(blank=True, max_length=100, null=True)),
                ('embarazada', models.CharField(blank=True, max_length=100, null=True)),
                ('higiene', models.CharField(blank=True, max_length=1, null=True)),
                ('numero_cepillados', models.CharField(blank=True, max_length=30, null=True)),
                ('alimentacion', models.CharField(blank=True, max_length=1, null=True)),
                ('integrantes_casa', models.CharField(blank=True, max_length=20, null=True)),
                ('practica_deportes', models.CharField(blank=True, max_length=20, null=True)),
                ('habito_adiccion', models.CharField(blank=True, max_length=100, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=100, null=True)),
                ('presion', models.CharField(blank=True, max_length=100, null=True)),
                ('pulso', models.CharField(blank=True, max_length=100, null=True)),
                ('tratamientos_odontologicos', models.CharField(blank=True, max_length=100, null=True)),
                ('alergico_anestesia', models.CharField(blank=True, max_length=100, null=True)),
                ('experiencia_tratamientos', models.CharField(blank=True, max_length=100, null=True)),
                ('articulacion_temporo', models.CharField(blank=True, max_length=100, null=True)),
                ('dolor_articulacion', models.BooleanField(default=False)),
                ('chasquidos', models.BooleanField(default=False)),
                ('limitacion_apertura', models.BooleanField(default=False)),
                ('limitacion_moviientos', models.BooleanField(default=False)),
                ('bruxismo', models.BooleanField(default=False)),
                ('obervaciones', models.TextField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(default='A', max_length=2)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente')),
            ],
        ),
    ]
