# Generated by Django 3.1.5 on 2021-02-13 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='id_doctor',
            new_name='doctor',
        ),
        migrations.AlterField(
            model_name='presupaciente',
            name='vence',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 15, 49, 48, 810881)),
        ),
    ]
