# Generated by Django 3.1.2 on 2021-01-16 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_auto_20210116_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupaciente',
            name='vence',
            field=models.DateField(default=datetime.datetime(2021, 2, 15, 19, 19, 55, 625406)),
        ),
    ]
