# Generated by Django 3.1.5 on 2021-02-12 22:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetPresupuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obervacion', models.CharField(max_length=120)),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.articulos')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('creado', models.DateTimeField(auto_created=datetime.datetime(2021, 2, 12, 22, 10, 45, 334107))),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.TextField(max_length=256)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=3)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(max_length=2)),
                ('id_det_ventas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.detpresupuesto')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('creado', models.DateTimeField(auto_created=datetime.datetime(2021, 2, 12, 22, 10, 45, 332905))),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.TextField(max_length=256)),
                ('fecha_presupuesto', models.DateTimeField(auto_now_add=True)),
                ('fecha_vence', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=3)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(max_length=2)),
                ('id_det_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.detpresupuesto')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetVentas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obervacion', models.CharField(max_length=120)),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.articulos')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
