# Generated by Django 3.1.2 on 2021-01-06 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20210106_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='creado',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 1, 6, 3, 37, 14, 358034)),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='creado',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 1, 6, 3, 37, 14, 360172)),
        ),
    ]
