# Generated by Django 3.0.6 on 2020-06-27 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20200627_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='creado',
            field=models.DateTimeField(auto_created=datetime.datetime(2020, 6, 27, 22, 44, 26, 884095)),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='creado',
            field=models.DateTimeField(auto_created=datetime.datetime(2020, 6, 27, 22, 44, 26, 886550)),
        ),
    ]
