# Generated by Django 3.0.6 on 2020-06-29 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_auto_20200628_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='creado',
            field=models.DateTimeField(auto_created=datetime.datetime(2020, 6, 29, 15, 29, 19, 49976)),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='creado',
            field=models.DateTimeField(auto_created=datetime.datetime(2020, 6, 29, 15, 29, 19, 51769)),
        ),
    ]
