# Generated by Django 3.1.5 on 2021-02-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=60)),
                ('estatus', models.CharField(default='A', max_length=2)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Compuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_articulo', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Fabricantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=60)),
                ('estatus', models.CharField(default='A', max_length=2)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=30)),
                ('porcentaje', models.FloatField(blank=True, max_length=4, null=True)),
                ('estatus', models.CharField(default='A', max_length=2)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=60)),
                ('estatus', models.CharField(default='A', max_length=2)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=60)),
                ('estatus', models.CharField(default='A', max_length=2)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
                ('clave', models.CharField(default='0', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('descripcion', models.CharField(max_length=120)),
                ('codigobarras', models.CharField(max_length=30)),
                ('precioventa', models.FloatField(max_length=14)),
                ('costo', models.FloatField(max_length=14)),
                ('stock_min', models.IntegerField(default=0)),
                ('stock_max', models.IntegerField(default=0)),
                ('reorden', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('estatus', models.CharField(default='A', max_length=2)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.categorias')),
                ('id_fabricantes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.fabricantes')),
                ('id_impuestos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.impuestos')),
                ('id_marcas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.marcas')),
                ('id_proveedores', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedores')),
                ('id_unidades', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.unidades')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
