# Generated by Django 3.0.6 on 2020-06-20 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='creado',
            field=models.DateTimeField(auto_created=datetime.datetime(2020, 6, 20, 2, 54, 58, 679143)),
        ),
    ]
