# Generated by Django 3.0.6 on 2020-06-20 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_auto_20200620_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricantes',
            old_name='fabricante',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='marcas',
            old_name='marca',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='unidades',
            old_name='unidad',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='articulos',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='creado',
            field=models.DateTimeField(auto_created=datetime.datetime(2020, 6, 20, 21, 43, 41, 5582)),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='reorden',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='stock_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='stock_min',
            field=models.IntegerField(),
        ),
    ]
