# Generated by Django 3.0.6 on 2020-06-26 23:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_auto_20200620_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_articulo', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RenameField(
            model_name='impuestos',
            old_name='impuesto',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='impuestos',
            name='pocertanje',
        ),
        migrations.AddField(
            model_name='articulos',
            name='compuesto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='impuestos',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='creado',
            field=models.DateTimeField(auto_created=datetime.datetime(2020, 6, 26, 23, 0, 39, 40489)),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='estatus',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='estatus',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='fabricantes',
            name='estatus',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='impuestos',
            name='estatus',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='estatus',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='estatus',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='estatus',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='articulos',
            name='id_compuesto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='inventarios.Compuesto'),
        ),
    ]
