# Generated by Django 3.0.6 on 2020-06-28 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0008_auto_20200627_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='creado',
            field=models.DateTimeField(auto_created=datetime.datetime(2020, 6, 28, 5, 23, 23, 28441)),
        ),
    ]
