# Generated by Django 3.0.6 on 2020-06-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=10)),
                ('motivo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion', models.DateField(auto_now_add=True)),
                ('atendio', models.CharField(max_length=5)),
                ('observacion', models.TextField(max_length=512)),
                ('estatus', models.CharField(max_length=2)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
