# Generated by Django 3.0.6 on 2020-06-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='paciente',
            new_name='id_paciente',
        ),
    ]
