# Generated by Django 3.0.6 on 2020-06-20 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('citas', '0002_auto_20200609_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente'),
        ),
    ]
