# Generated by Django 3.1.5 on 2021-02-12 22:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=80)),
                ('estatus', models.CharField(default='A', max_length=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('apellidos', models.CharField(default='', max_length=50)),
                ('correo', models.CharField(default='', max_length=100)),
                ('fecha_nat', models.DateTimeField(default=datetime.datetime.now)),
                ('sexo', models.CharField(default='', max_length=12)),
                ('cp', models.CharField(default='', max_length=6)),
                ('callenum', models.CharField(default='', max_length=50)),
                ('colonia', models.CharField(default='', max_length=40)),
                ('ciudad', models.CharField(default='', max_length=40)),
                ('estado', models.CharField(default='', max_length=40)),
                ('pais', models.CharField(default='', max_length=20)),
                ('telefono_particular', models.CharField(default='', max_length=20)),
                ('celular', models.CharField(default='', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(default='A', max_length=1)),
                ('observaciones', models.CharField(default='', max_length=255)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.especialidad')),
            ],
        ),
    ]
