# Generated by Django 3.1.2 on 2021-01-06 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=80)),
                ('estatus', models.CharField(default='A', max_length=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('telefono_partucular', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(default='A', max_length=1)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.especialidad')),
            ],
        ),
    ]
