# Generated by Django 3.1.2 on 2021-01-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctores',
            old_name='telefono_partucular',
            new_name='telefono_particular',
        ),
    ]
