# Generated by Django 3.1.2 on 2021-01-16 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20210106_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctores',
            name='direccion',
        ),
        migrations.AddField(
            model_name='doctores',
            name='callenum',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='doctores',
            name='ciudad',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='doctores',
            name='colonia',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='doctores',
            name='correo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctores',
            name='cp',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='doctores',
            name='estado',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='doctores',
            name='fecha_nat',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='doctores',
            name='observaciones',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctores',
            name='pais',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doctores',
            name='sexo',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='doctores',
            name='apellidos',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctores',
            name='celular',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctores',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='doctores',
            name='telefono_particular',
            field=models.CharField(default='', max_length=20),
        ),
    ]
