# Generated by Django 3.0.6 on 2020-06-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('cp', models.CharField(blank=True, default='', max_length=8, null=True)),
                ('estado', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('municipio', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('colonia', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('calle', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('web', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('celular', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, default='', null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(default='A', max_length=2)),
            ],
        ),
    ]
